Repository SOPT33-SOPKATHON/Server, pull requests merged in 2023-11, with the labels that each got.

#2 [CHORE] 초기 세팅 및 README.md 작성
  README.md
  src/main/java/com/sopt/sopkathonServer/common/config/JpaAuditingConfig.java
  src/main/java/com/sopt/sopkathonServer/common/config/WebConfig.java
  src/main/java/com/sopt/sopkathonServer/common/domain/BaseTimeEntity.java
  src/main/java/com/sopt/sopkathonServer/common/dto/ApiResponse.java
  src/main/java/com/sopt/sopkathonServer/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sopt/sopkathonServer/common/exception/TestController.java
  src/main/java/com/sopt/sopkathonServer/common/exception/enums/ErrorType.java
  src/main/java/com/sopt/sopkathonServer/common/exception/enums/SuccessType.java
  src/main/java/com/sopt/sopkathonServer/common/exception/model/BusinessException.java
  src/main/resources/application.yml
Labels: 🧹Chore, 동섭🍋, 📃Docs, 🔥 Pull Request

#4 [FEAT] entity 정의
  src/main/java/com/sopt/sopkathonServer/celeb/domain/Celeb.java
  src/main/java/com/sopt/sopkathonServer/celeb/domain/PostIt.java
  src/main/java/com/sopt/sopkathonServer/room/domain/Room.java
  src/main/java/com/sopt/sopkathonServer/user/domain/User.java
Labels: ☁️Database, 동섭🍋, 🔥 Pull Request, 경린🍇

#5 [FEAT] 축하 메시지 ì생성
  src/main/java/com/sopt/sopkathonServer/celeb/controller/CelebController.java
  src/main/java/com/sopt/sopkathonServer/celeb/domain/Celeb.java
  src/main/java/com/sopt/sopkathonServer/celeb/domain/PostIt.java
  src/main/java/com/sopt/sopkathonServer/celeb/dto/request/CelebCreateRequest.java
  src/main/java/com/sopt/sopkathonServer/celeb/dto/response/CelebCreateResponse.java
  src/main/java/com/sopt/sopkathonServer/celeb/repository/CelebJpaRepository.java
  src/main/java/com/sopt/sopkathonServer/celeb/service/CelebService.java
  src/main/java/com/sopt/sopkathonServer/common/exception/enums/ErrorType.java
  src/main/java/com/sopt/sopkathonServer/common/exception/enums/SuccessType.java
  src/main/java/com/sopt/sopkathonServer/room/repository/RoomJpaRepository.java
  src/main/java/com/sopt/sopkathonServer/room/service/RoomService.java
Labels: ✨Feat, 동섭🍋, 경린🍇

#8 [FEAT]방 가져오기 기능 추가
  src/main/java/com/sopt/sopkathonServer/common/exception/enums/SuccessType.java
  src/main/java/com/sopt/sopkathonServer/room/controller/RoomController.java
  src/main/java/com/sopt/sopkathonServer/room/domain/Room.java
  src/main/java/com/sopt/sopkathonServer/room/dto/response/RoomGetResponse.java
  src/main/java/com/sopt/sopkathonServer/room/repository/RoomJpaRepository.java
  src/main/java/com/sopt/sopkathonServer/room/service/RoomService.java
Labels: ✨Feat, 동섭🍋, 경린🍇
